function generateHTML() {
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>360 view</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    
    <body>
            <div style="display: none !important;">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/0.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/1.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/2.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/3.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/4.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/5.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/6.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/7.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/8.png" alt=""> 
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/9.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/10.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/11.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/12.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/13.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/14.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/15.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/16.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/17.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/18.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/19.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/20.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/21.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/22.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/23.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/24.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/25.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/26.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/27.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/28.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/29.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/30.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/31.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/32.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/33.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/34.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/35.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/36.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/37.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/38.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/39.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/40.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/41.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/42.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/43.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/44.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/45.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/46.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Gris/47.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/0.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/1.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/2.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/3.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/4.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/5.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/6.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/7.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/8.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/9.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/10.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/11.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/12.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/13.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/14.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/15.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/16.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/17.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/18.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/19.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/20.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/21.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/22.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/23.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/24.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/25.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/26.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/27.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/28.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/29.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/30.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/31.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/32.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/33.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/34.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/35.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/36.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/37.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/38.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/39.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/40.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/41.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/42.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/43.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/44.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/45.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/46.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Azul/47.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/0.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/1.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/2.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/3.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/4.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/5.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/6.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/7.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/8.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/9.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/10.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/11.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/12.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/13.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/14.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/15.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/16.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/17.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/18.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/19.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/20.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/21.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/22.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/23.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/24.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/25.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/26.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/27.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/28.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/29.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/30.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/31.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/32.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/33.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/34.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/35.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/36.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/37.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/38.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/39.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/40.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/41.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/42.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/43.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/44.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/45.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/46.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/GrisPurpura/47.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/0.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/1.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/2.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/3.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/4.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/5.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/6.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/7.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/8.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/9.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/10.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/11.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/12.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/13.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/14.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/15.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/16.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/17.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/18.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/19.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/20.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/21.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/22.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/23.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/24.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/25.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/26.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/27.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/28.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/29.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/30.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/31.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/32.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/33.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/34.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/35.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/36.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/37.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/38.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/39.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/40.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/41.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/42.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/43.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/44.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/45.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/46.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Rojo/47.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/0.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/1.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/2.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/3.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/4.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/5.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/6.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/7.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/8.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/9.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/10.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/11.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/12.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/13.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/14.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/15.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/16.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/17.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/18.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/19.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/20.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/21.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/22.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/23.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/24.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/25.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/26.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/27.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/28.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/29.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/30.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/31.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/32.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/33.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/34.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/35.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/36.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/37.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/38.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/39.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/40.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/41.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/42.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/43.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/44.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/45.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/46.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/Coolray/Blanco/47.png" alt="">
            </div>

    </body>
    </html>
    `;
}

generateHTML();
