export function generateHTML() {
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>360 view</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    
    <body>
            
            <div style="display: none !important;">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/0.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/1.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/2.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/3.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/4.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/5.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/6.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/7.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/8.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/9.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/10.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/11.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/12.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/13.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/14.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/15.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/16.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/17.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/18.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/19.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/20.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/21.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/22.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/23.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/24.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/25.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/26.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/27.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/28.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/29.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/30.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/31.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/32.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/33.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/34.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/35.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/36.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/37.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/38.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/39.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/40.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/41.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/42.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/43.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/44.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/45.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/46.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Negro/47.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/0.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/1.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/2.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/3.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/4.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/5.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/6.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/7.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/8.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/9.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/10.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/11.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/12.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/13.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/14.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/15.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/16.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/17.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/18.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/19.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/20.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/21.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/22.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/23.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/24.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/25.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/26.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/27.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/28.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/29.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/30.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/31.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/32.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/33.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/34.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/35.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/36.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/37.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/38.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/39.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/40.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/41.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/42.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/43.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/44.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/45.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/46.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Azul/47.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/0.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/1.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/2.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/3.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/4.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/5.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/6.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/7.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/8.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/9.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/10.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/11.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/12.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/13.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/14.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/15.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/16.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/17.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/18.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/19.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/20.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/21.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/22.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/23.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/24.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/25.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/26.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/27.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/28.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/29.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/30.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/31.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/32.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/33.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/34.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/35.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/36.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/37.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/38.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/39.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/40.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/41.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/42.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/43.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/44.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/45.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/46.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Purpura/47.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/0.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/1.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/2.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/3.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/4.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/5.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/6.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/7.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/8.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/9.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/10.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/11.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/12.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/13.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/14.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/15.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/16.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/17.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/18.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/19.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/20.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/21.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/22.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/23.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/24.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/25.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/26.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/27.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/28.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/29.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/30.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/31.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/32.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/33.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/34.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/35.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/36.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/37.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/38.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/39.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/40.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/41.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/42.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/43.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/44.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/45.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/46.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Gris/47.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/0.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/1.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/2.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/3.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/4.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/5.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/6.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/7.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/8.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/9.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/10.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/11.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/12.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/13.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/14.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/15.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/16.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/17.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/18.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/19.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/20.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/21.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/22.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/23.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/24.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/25.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/26.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/27.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/28.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/29.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/30.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/31.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/32.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/33.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/34.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/35.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/36.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/37.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/38.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/39.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/40.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/41.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/42.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/43.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/44.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/45.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/46.png" alt="">
                <img src="https://raw.githubusercontent.com/minusdigital/360widget/main/Models/GeometryC/Blanco/47.png" alt="">
            </div>

    </body>
    </html>
    `;
}

